---
name: CI Verify Ansible roles with molecule
"on":
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7 * * 0"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install lint dependencies.
        run: pip3 install yamllint
      - name: Lint code.
        run: |
          yamllint .
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - geerlingguy/docker-centos7-ansible:latest
          - geerlingguy/docker-centos8-ansible:latest
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
          - centos7
          - centos8
      fail-fast: false

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install test dependencies.
        run: |
          python -m pip install --upgrade pip
          pip3 install ansible ansible-lint molecule-plugins[docker] docker
      - name: Run Molecule tests.
        run: molecule test
        working-directory: ${{env.working-directory}}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          ANSIBLE_VERBOSITY: '2'
          MOLECULE_DEBUG: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
